
3
4
5
6
7
8
9
10
11
12
13
 
version: '3.9'
services:
  fastapi-sample:
    build:
      target: dev
    volumes:
      - ./backend:/usr/src/fastapi_sample/backend
    ports:
      - 2003:2003
    environment:
      - PORT=2003