
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
 
version: '3.9'
services:
  fastapi-sample:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    image: fastapi-sample
    working_dir: /usr/src/fastapi_sample
    command: &gt;
      pipenv run gunicorn backend.main:app
      --config './backend/gunicorn.conf.py'
    volumes:
      - ./logs:/usr/src/fastapi_sample/logs
    environment:
      - TZ=Asia/Tokyo
    restart: always