FROM ubuntu:20.04
LABEL description="inkscpaeのAPIサーバー"
WORKDIR /api
RUN apt update
RUN apt install -y software-properties-common 
RUN add-apt-repository -y ppa:inkscape.dev/stable
RUN sudo apt -y install inkscape